### ISSUE TITLE
Logstash 2.3.4 and Throttle Filter

### ISSUE THREAD

**Issue by tocaleb** [logstash-plugins/logstash-filter-throttle#14]
Am I correct in understanding  that the throttle filter plugin has been updated so that it is thread-safe (IE I should be able to utilize multiple workers?)

When I try to update , however, this fails with little information:

> logstash-plugin update logstash-filter-throttle
> You are updating logstash-filter-throttle to a new version 4.0.0, which may notbe compatible with 2.0.4. are you sure you want to proceed (Y/N)?
> Y
> 
> Updating logstash-filter-throttle
> No plugins updated.

Does this mean that the higher version of the Filter plugin is not supported? I'd really like to update as my number of worker threads gets set back to 1 due to the usage of the throttle filter.

> Defaulting pipeline worker threads to 1 because there are some filters that might not work with multiple worker threads {:count_was=>2, :filters=>["throttle", "throttle"], :level=>:warn}
> Pipeline main started

Thanks in advance for any help that can be provided

**Comment by suyograo** [comment]
@tocaleb yes throttle filter has been updated for Logstash 5.0, but it has not been backported to support LS 2.x. Also, it is a breaking change.

**Comment by suyograo** [comment]
Our plans are to release LS 2.4 which will allow users to install plugins written in LS 5.0

**Comment by tocaleb** [comment]
Great, thank you so much for your response
