### ISSUE TITLE
Key => multiple fields issue

### ISSUE THREAD

**Issue by Sjaak01** [logstash-plugins/logstash-filter-throttle#19]
Hello,

I'm having an issue with the key value that I cannot figure out.

- I noticed that %{field} logs every unique value per whatever throttle time you configure
- I noticed "field" logs only 1 message per whatever throttle time you configure
- I also noticed you need to put ALL your fields in the key value otherwise fields not there will not be logged at all (unexpected behavior, I expected fields not mention under key => would be ignored an go through as normal)

I am logging various fields from a device. Some fields (error) I want to log each unique error at a 30 minute per error interval.

This works using %{error}.

I've got a GPS field that I want to log only once every 30 minutes regardless of the actual value. 

This works using "field".

I can even combine that into key => "%{error}%gps" which works.

However a combination such as

"%{error}%{host}%speed%gps

results in the %speed field never getting logged, it gets ignored.

How do I need to configure the "key" value to log messages the way I want? I've checked the docs on the elastic website but they don't mention anything about this.

**Comment by jsvd** [comment]
I'm not sure what you mean with %gps, that is not a field reference and will just be evaluated as a string `"%gps"`

whatever is put into `:key` is used to partition the data and decide, for each value, if things should be throttled or not.

**Comment by jsvd** [comment]
That said, I apologize for the inconvenience, but I believe this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.
