### ISSUE TITLE
Use before_count > after_count

### ISSUE THREAD

**Issue by duylong** [logstash-plugins/logstash-filter-throttle#3]
Hi,

We can not use this case: 

```
throttle {
  after_count => 5
  before_count => 6
  ...
}
```

When "before_count" greater than "after_count", "after_count" is never considered.

**Comment by frapex** [comment]
That is an invalid range. Works as designed.

Invalid range:

```
puts (5..6).to_a
```

Result:

```
(nothing returned)
```

Good range:

```
puts (5..6).to_a
```

Result:

```
5
6
```
