### ISSUE TITLE
setting threadsafe to false must be done in initialize and not in register

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-filter-throttle#6]
Setting `@threadsafe = false` in the register bypasses the pipeline initialization checks for non thread safe plugins if -w > 1
This means that if -w > 1 this plugin will start and will therefore be subject to race conditions and other problems.

So instead of https://github.com/logstash-plugins/logstash-filter-throttle/blob/master/lib/logstash/filters/throttle.rb#L149-L150, it should be more like https://github.com/logstash-plugins/logstash-filter-multiline/blob/master/lib/logstash/filters/multiline.rb#L124-L130

**Comment by frapex** [comment]
logstash-filter-throttle is multithreaded since v4.0.0 (pull request: https://github.com/logstash-plugins/logstash-filter-throttle/pull/5). Issue can be closed.
