### ISSUE TITLE
It this plugin running on one thread?

### ISSUE THREAD

**Issue by jaap-stack** [logstash-plugins/logstash-filter-throttle#7]
When I use Logstash without the filter my Logstash agent takes up around 270% CPU, which is normal (it has 4 cores). 

When I enable the throttle plugin it takes up 100% CPU and is not able anymore to process the load. 

It seems that the throttle plugin caps the CPU usage in some way, perhaps working singlethreaded. I would like the plugin to take full advantage of all my available cores. 

Red Hat Enterprise Linux Server release 6.7 (Santiago)
logstash 2.2.0

**Comment by Hikariii** [comment]
Your observations are correct, see https://github.com/logstash-plugins/logstash-filter-throttle/pull/1 and related issue https://github.com/elastic/logstash/pull/1469 for the conversation.
Currently there is nobody planning on fixing this, so if you want to...

**Comment by frapex** [comment]
logstash-filter-throttle is multithreaded since v4.0.0 (pull request: https://github.com/logstash-plugins/logstash-filter-throttle/pull/5). Issue can be closed.
